# 多环境配置文件激活属性
spring:
  datasource:
    url: jdbc:mysql://123.60.36.218:3306/car_rental?useUnicode=true&characterEncoding=utf8
    username: carrental
    password: Zjy@202101
    driver-class-name: com.mysql.jdbc.Driver